intra/front/urls.py
from django.urls import register_converter, path
from . import views
from . import views_settings

class NegativeIntConverter:
    regex = '-?\d+'

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return '%d' % value

register_converter(NegativeIntConverter, 'negint')

app_name = "front"
urlpatterns = [
     path("", views.LoginView.as_view(), name="top"),
     path("logout", views.LogoutView.as_view(), name="logout"),
     path("home", views.HomeView.as_view(), name="home"),
     path("board", views.BoardView.as_view(), name="board_menu"),
     path("board/new", views.BoardCreateView.as_view(), name="board_create"),
     path("board/<str:id>",
          views.Board_detailView.as_view(),
          name="board_detail"),
     path("board/<str:id>/comment",
         views.BoardComment.as_view(),
         name="board_comment"),
     path("board/<str:id>/good",
         views.BoardGood.as_view(),
         name="board_good"),
     path("attend/<int:year>/<int:month>",
          views.AttendView.as_view(),
          name="attend"),
     path("attend-info/<int:year>/<int:month>",
          views.attend_info,
          name="attend_info"),
     path("attend/<int:year>/<int:month>/<int:day>",
          views.AttendRegisterDay.as_view(),
          name="attend_register_day"),
     path("approval", views.ApprovalView.as_view(), name="approval"),
     path("approval/check/<str:id>",
          views.Approval_checkView.as_view(), name="approval_check"),
     path("approval/new/<int:id>",
          views.NewApprovalView.as_view(), name="new_approval"),
     path('signup/', views.signupView.as_view(), name='signup'),
     path('signup/register',
          views.signup_Register.as_view(),
          name='signup_register'),
     path("tools", views.ToolsView.as_view(), name="tools"),
     path("setting", views_settings.SettingView.as_view(), name="setting"),
     path("setting/work_status", views_settings.SettingWorkStatusView.as_view(),
          name="setting_work_status"),
     path("setting/work_status/<int:id>", views_settings.SettingWorkStatusViewById.as_view(),
          name="setting_work_status_by_id"),
     path("setting/holiday", views_settings.SettingHolidayView.as_view(),
          name="setting_holiday"),
     path("setting/holiday/info", views_settings.SettingHolidayInfo.as_view(),
          name="setting_holiday_info"),
     path("setting/holiday/<str:date>", views_settings.SettingHolidayByDate.as_view(),
          name="setting_holiday_by_date"),
     path("setting/user",
          views_settings.SettingUserView.as_view(),
          name="setting_user"),
     path("setting/user/<int:id>", views_settings.SettingUserById.as_view(),
          name="setting_user_by_id"),
     path("setting/approval_format/<int:id>",
          views_settings.SettingApprovalFormatView.as_view(),
          name="setting_approval_format"),
     path("userinfo",
          views.UserInfo.as_view(),
          name="user_info"),
]

intra/intra/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('front.urls')),
    path('admin/', admin.site.urls),
]

intra/front/forms.py
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,forms
from django.contrib.auth.models import User
from django import forms
from .models import WorkStatus
from django.core.exceptions import ValidationError

class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username','last_name','first_name','email', 'password1', 'password2')
        
        
#class workStatusForm(forms.Form):
#    answers = forms.fields.ChoiceField(
#        choices = (
#            (1, 1),
#            (11, 11),
#            (999, 'ALL')
#        ),
#        initial=10,
#        required=True,
#        widget=forms.widgets.Select()
#    )


class WorkStatusForm(forms.ModelForm):
    
    class Meta:
        model = WorkStatus
        # fields = ('status', 'name','name_selection','use')
        fields = '__all__'
        labels = {
            'status': '勤怠区分コード',
            'name': '勤怠区分名',
            'name_selection': '勤怠区分(プルダウン表示)',
            'use': '使用可否',
        }
        help_texts = {
            'status': '２桁の整数',
            'name': '１０文字以内',
            'name_selection': '２文字',
        }
        
        def check_name_selection(value):
            if len(value)>3:
                raise ValidationError('プルダウン表示は３文字以内で入力してください。')

intra/front/views.py
import calendar
import datetime
import json
from logging import getLogger
from typing import Any

from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.db.models import (
    Max,
)
from django.forms.models import model_to_dict
from django.utils.timezone import make_aware
from django.contrib.auth.models import User
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
)
from django.contrib.auth import login
from django.contrib.auth.views import (
    LoginView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    View,
    TemplateView
)
from django.views.generic.edit import (
    CreateView,
    FormView
)
from django.shortcuts import render
from django.urls import reverse_lazy

from . import forms
from .common import (
    get_workStatus,
    nvl,
    get_d_h_m_s,
    second2time
)
from .consts import (
    WEEKDAYS,
    MAP_APPROVAL_STATUS,
    APPROVAL_STATUS_CODE
)
from .models import (
    Attendance,
    WorkStatus,
    UserSetting,
    Approval,
    Approval_route,
    Approval_format,
    Approval_format_route,
    Board,
    Board_comment,
)

logger = getLogger(__name__)


def is_admin():
    return True


def register_attendance_month(user_id, year, month):

    dayCnt = calendar.monthrange(year, month)[1]

    for i in range(dayCnt):

        date = make_aware(datetime.datetime(year, month, i+1))
        work_status = get_workStatus(date, user_id)
        sysmemo = ''
        if work_status['name']:
            sysmemo = f'★{work_status["name"]}'

        user = User.objects.get(id=user_id)

        b = Attendance(
            user=user,
            date=date,
            work_status=work_status['status'],
            work_start=date,
            work_end=date,
            sysmemo=sysmemo
        )
        b.save()

class BaseView(View):

    def _is_valid_user(self, user_id):
        """ユーザがログイン認証されているかどうかを判定する
        """
        user = User.objects.filter(id=user_id)
        if user.count() == 0:
            return False
        return user[0].is_authenticated

    def _is_permitted_function(self, user_id, permissions: list):
        """ユーザが指定された機能の権限を持っているかを判定する
        """
        user = User.objects.get(id=user_id)
        return user.get_user_permissions(permissions)


class TopView(TemplateView):
    template_name = "front/top.html"


class HomeView(LoginRequiredMixin, TemplateView):

    def get(self, request):

        user = User.objects.get(id=request.user.id)

        # 決裁ルートに自身がいて、かつ自身の決裁待ちであるデータを抽出
        approval_routes = Approval_route.objects.filter(user=user, status=2)
        need_check = {}
        for approval_route in approval_routes:
            need_check[approval_route.approval.id] = approval_route.approval

        params = {'message': '',
                  'need_check': need_check,
                  }

        return render(request, 'front/home.html', params)


class ApprovalView(BaseView):

    def get(self, request):

        if not self._is_valid_user(request.user.id):
            return render(request, 'front/no_session.html', status=403)

        user = User.objects.get(id=request.user.id)
        field = Approval._meta._get_fields()
        complete_status_min = 5

        # 未完了の決裁
        data = Approval.objects.filter(
            user=user, status__lt=complete_status_min
            ).select_related('user')
        approval = {}
        for obj in data:

            # q = Approval_route.objects.filter(approval_id=obj.id)
            status = MAP_APPROVAL_STATUS[obj.status]

            approval[obj.id] = {'approval': obj,
                                'status': status,
                                'route': obj.related_route.all(),
                                }

        # 完了済の決裁
        data_complete = Approval.objects.filter(
            user=user, status__gte=complete_status_min)
        approval_complete = {}
        for obj in data_complete:
            status = MAP_APPROVAL_STATUS[obj.status]

            # なぜかdateだけmodel_to_dictのとき抜け落ちるので、自分で入れる（多分migrateで関連付けが失敗してる）
            obj_dict = model_to_dict(obj)
            obj_dict['date'] = obj.date

            approval_complete[obj.id] = {'approval': obj_dict,
                                         'status': status,
                                         'route': obj.related_route.all(),
                                         }

        # 決裁ルートに自身がいて、かつ自身の決裁待ちであるデータを抽出
        q = Approval_route.objects.filter(user=user, status=2)
        need_check = {}
        for obj in q:
            need_check[obj.approval.id] = obj.approval

        params = {
            'message': '一覧',
            'data': data,
            'field': field,
            'user': request.user,
            'approval': approval,
            'approval_complete': approval_complete,
            'page_approval': 1,
            'need_check': need_check,
        }

        return render(request, 'front/approval.html', params)


class NewApprovalView(BaseView):

    def post(self, request, id, *args, **kwargs):

        datas = json.loads(request.body)
        user = User.objects.get(id=request.user.id)

        with transaction.atomic():
            b = Approval(
                user=user,
                title=datas.get('title'),
                detail=datas.get('detail'),
                date=datetime.date.today(),
            )
            b.save()

            new_approval = Approval.objects.all().order_by("-id")[0]

            # route
            route = datas.get('route')

            for cnt, user_id in enumerate(route):

                if cnt == 0:
                    status = APPROVAL_STATUS_CODE.MYTURN.value
                else:
                    status = APPROVAL_STATUS_CODE.WAITMYTURN.value
                
                user = User.objects.get(id=user_id)

                b = Approval_route(
                    approval=new_approval,
                    user=user,
                    status=status,
                )
                b.save()

        return JsonResponse({'reload': True})


class Approval_checkView(BaseView):

    def get(self, request, id, *args, **kwargs):

        if not self._is_valid_user(request.user.id):
            return render(request, 'front/no_session.html', status=403)

        data = Approval.objects.get(id=id)
        approval_route = data.related_route
        route = list()
        for r in approval_route.all():
            route.append(
                dict(name=f'{r.user.last_name}{r.user.first_name}',
                     comment=r.comment,
                     id=r.id))
        return JsonResponse({
            'data': model_to_dict(data),
            'route': route,
            })

    def post(self, request, id, *args, **kwargs):

        with transaction.atomic():
            datas = json.loads(request.body)
            user = User.objects.get(id=request.user.id)
            status = datas.get('status')
            comment = datas.get('comment')

            target_approval = Approval.objects.get(id=id)
            target_approval_route = target_approval.related_route.get(
                status=APPROVAL_STATUS_CODE.MYTURN.value, user=user)

            if status != 0:
                target_approval_route.status = status
                target_approval_route.approved_date = datetime.date.today()
                target_approval_route.comment = comment
                target_approval_route.save()

                next_route = target_approval.related_route.filter(status=APPROVAL_STATUS_CODE.WAITMYTURN.value).order_by("id")

                if next_route.count() == 0 or \
                        status in [APPROVAL_STATUS_CODE.REJECT.value, APPROVAL_STATUS_CODE.CANCEL.value]:
                    # 却下か取り下げされた場合もしくは最終承認者であった場合、この決裁自体が完了となる
                    target_approval.status = status
                    target_approval.date_complete = datetime.date.today()
                    target_approval.save()
                else:
                    # 次の人の承認ステータスも承認待ちに更新
                    target_next_route = Approval_route.objects.get(id=next_route[0].id)
                    target_next_route.status = APPROVAL_STATUS_CODE.MYTURN.value
                    target_next_route.save()

        return JsonResponse({'reload': True})


class BoardView(BaseView):
    def get(self, request, *args, **kwargs):

        if not self._is_valid_user(request.user.id):
            return render(request, 'front/no_session.html', status=403)

        board_items = Board.objects.all()

        datas = list()
        for d in board_items:
            board = model_to_dict(d)
            user = {
                'id': d.user.id,
                'first_name': d.user.first_name,
                'last_name': d.user.last_name,
            }
            board_comments = d.board_comments.all()
            board['user'] = user
            board['comment_count'] = len(board_comments)
            datas.append(board)

        params = {
            'title': '掲示板一覧',
            'datas': datas,
            'user': request.user,
            'page_board': 1,
        }

        return render(request, "front/board.html", params)

class BoardCreateView(BaseView):

    def get(self, request, *args, **kwargs):

        if not self._is_valid_user(request.user.id):
            return render(request, 'front/no_session.html', status=403)

        params = {
        }

        return render(request, "front/board_detail.html", params)

    def post(self, request, *args, **kwargs):

        datas = json.loads(request.body)
        user = User.objects.get(id=request.user.id)
        b = Board(
            title=datas.get('title'),
            detail=datas.get('detail'),
            user=user,
        )
        b.save()
        return JsonResponse({'result': True})

class Board_detailView(BaseView):

    def get(self, request, id, *args, **kwargs):

        if not self._is_valid_user(request.user.id):

intra/front/templates/front/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
  <link rel="stylesheet" href="{% static 'css/icon.css' %}">
  <link rel="stylesheet" href="/static/uikit/css/uikit.css">
  <script src="/static/uikit/js/uikit.min.js"></script>
  <script src="/static/uikit/js/uikit-icons.min.js"></script>
  <script src="/static/js/common.js"></script>
  <title>{% block title %}{% endblock %}</title>

  {% block head %}{% endblock %}
</head>

<body>
  <header>
    {% block header %}{% endblock %}
  </header>

  <div class="content-main">
    {% block content %}{% endblock %}
  </div>

  <footer>
    {% block footer %}{% endblock %}
  </footer>
</body>

</html>

intra/front/templates/front/base_account.html
<!doctype html>
{% load static %}
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}{% endblock %}</title>

    {% block header %}{% endblock%}
  </head>
  <body>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    
    <!-- MenuBar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="{% url 'front:top' %}">
        <img src="{% static 'images/head.jpg' %}" alt="Home" width="50" height="50">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      
    </nav>

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  </body>
</html>

intra/front/templates/front/base_nav.html
{% extends "front/base.html" %}
{% load static %}


{% block header %}
<nav class="uk-navbar-container">
  <div class="uk-container">
    <div uk-navbar>
      <div class="uk-navbar-left">

        <ul class="uk-navbar-nav">
          <li>
            <a href="{% url 'front:home' %}">
              <img src="{% static 'images/home.jpg' %}" alt="Home" width="50px" height="50px">
            </a>
          </li>
          <li>
            <a id="{% url 'front:home' %}" href="{% url 'front:home' %}">Home</a>
          </li>
          <li>
            <a id="" href="#" onclick="moveToAttend()">勤怠入力</a>
          </li>
          <li>
            <a id="{% url 'front:board_menu' %}" href="{% url 'front:board_menu' %}">掲示板</a>
          </li>
          <li>
            <a id="{% url 'front:approval' %}" href="{% url 'front:approval' %}">決裁</a>
          </li>
          <li>
            <a id="{% url 'front:tools' %}" href="{% url 'front:tools' %}">Tools</a>
          </li>
          <li>
            <a id="{% url 'front:setting' %}" href="{% url 'front:setting' %}">設定</a>
          </li>
        </ul>
      </div>
      <div class="uk-navbar-right">
        <ul class="uk-navbar-nav">
          {% if not page_signup and not page_login %}
          <li>
            <a href="javascript:void[0]">
              <img src="{% static 'images/user_image_sample.jpg' %}" class="img-icon">
            </a>
          </li>
          <li>
            <a href="javascript:void[0]">{{ request.user.last_name }}{{ request.user.first_name }}</a>
          </li>
          <li>
            <a href="{% url 'front:logout' %}">ログアウト</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>
{% csrf_token %}
<script type="text/javascript">

  //今日の日付データを変数に格納
  var today = new Date();

  //年・月・日・曜日を取得
  var baseYear = today.getFullYear();
  var baseMonth = today.getMonth() + 1;

  function moveToAttend() {
    location.href = "{% url 'front:attend' 91 92 %}".replace(/91/, baseYear).replace(/92/, baseMonth);
  };
</script>
{% endblock %}

intra/front/templates/front/index.html
{% extends "front/base.html" %}
{% block title %}ログイン{% endblock %}

{% block content %}


<div class="uk-container uk-position-center">
    <h1 class="uk-text-center"><span>ログイン</span></h1>

    <div class="uk-card uk-card-default uk-card-body">
        <div class="uk-card-body uk-text-center">
            <form action="?" method="POST">
                {% csrf_token %}

                <div>
                    <input type="text" placeholder="ユーザID" name="username" autofocus="" autocapitalize="none" autocomplete="username"
                        maxlength="150" class="uk-input" required="" id="id_username">
                </div>
                <br>
                <div>
                    <input type="password" placeholder="パスワード" name="password" autocomplete="current-password" class="uk-input" required=""
                        id="id_password">
                </div>
                <br>

                <button class="uk-button uk-button-primary uk-button-small" type="submit">ログイン</button>


                <br>
                <br>
                <a href="{% url 'front:signup' %}" class="button register">新規登録</a>
            </form>
        </div>
    </div>
</div>

<!-- <form action="?" method="POST">
        <div class="uk-grid-small uk-text-center" uk-grid>
            <div class="uk-card uk-card-default uk-card-body">

                <div class="uk-card-body">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                    {{ field.label }}
                    <br>
                    {{ field }}
                    <br>
                    {{ field.error }}
                    {% endfor %}
                    <br>
                    <button class="uk-button uk-button-primary uk-button-small" type="submit">ログイン</button>


                    <br>
                    <br>
                    <a href="{% url 'front:signup' %}" class="button register">新規登録</a>
                </div>
            </div>
        </div>
    </form> -->
</div>

<script>
    $('#button1').on('click', function () {
        // Ajax通信を開始
        $.ajax({
            url: "{% url 'front:test' %}",
            method: "GET",
            // プレーンテキストを受信（他にはhtml、xml、script、json、jsonp等）
            dataType: 'text',
            // リクエストパラメータ「?param1=いろはに&param2=ほへと&param3=ちりぬるを」
            data: {
                param1: 'いろはに',
                param2: 'ほへと',
                param3: 'ちりぬるを '
            },
            timeout: 5000,
        })
            .done(function (data) {
                // 通信成功時の処理を記述
                $('#resultGET').text('GET処理成功' + data);
            })
            .fail(function () {
                // 通信失敗時の処理を記述
                $('#resultGET').text('GET処理失敗.');
            });
    })
</script>
{% endblock %}

intra/front/templates/front/no_session.html
{% extends "front/base_account.html" %}

{% block title %}エラーページ{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">エラーページ</h1>

    ログインされていないか、セッションが有効期限切れです。
    再度<a class="uk-link-text" href="/">ログイン</a>してください。
</div>
{% endblock %}

intra/front/templates/front/setting.html
{% extends "front/base_nav.html" %}
{% block title %}設定{% endblock %}

{% block content %}

<div class="uk-container">
    <div class="uk-margin-medium-top">
        <ul class="uk-flex-center" uk-tab data-uk-tab="{connect:'#my-id'}">
            <li class="uk-active"><a href="#">勤怠区分設定</a></li>
            <li><a href="#">休日設定</a></li>
            <li><a href="#">ユーザ設定</a></li>
            <li><a href="#">決裁フォーマット</a></li>
        </ul>
        <ul id="my-id" class="uk-switcher uk-margin">
            <li>
                <div class="uk-cover-container uk-height-large" uk-height-viewport="expand: true">
                    <iframe src="{% url 'front:setting_work_status' %}" width="100%" height="100%"></iframe>
                </div>
            </li>
            <li>
                <div class="uk-cover-container uk-height-large" uk-height-viewport="expand: true">
                    <iframe src=" {% url 'front:setting_holiday' %}" width="100%" height="100%"></iframe>
                </div>
            </li>
            <li>
                <div class="uk-cover-container uk-height-large" uk-height-viewport="expand: true">
                    <iframe src=" {% url 'front:setting_user' %}" width="100%" height="100%"></iframe>
                </div>
            </li>
            <li>
                <div class="uk-cover-container uk-height-large" uk-height-viewport="expand: true">
                    <iframe src=" {% url 'front:setting_approval_format' 0 %}" width="100%" height="100%"></iframe>
                </div>
            </li>
        </ul>
    </div>
</div>

{% endblock %}

intra/front/templates/front/signup.html
{% extends "front/base_account.html" %}
{% block title %}新規登録{% endblock %}

{% block content %}
<div class="container">
    <h1>新規登録</h1>
    <form method="post" action="{% url 'front:signup_register' %}">
    {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            {{ field.label }}
            <br>
            {{ field }}
            <br>
            {{ field.error }}
        {% endfor %}
        <br>

        
        <input type="submit" class="btn btn-primary" value="登録" />








        <a href="{% url 'front:top' %}" class="btn btn-primary">戻る</a>
    </form>
</div>
{# エラーメッセージを表示 #}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p>{{ error }}</p>
        {% endfor %}
     {% endfor %}
{% endif %} 
</form>
{% endblock %}

intra/front/templates/front/tools.html
{% extends "front/base_nav.html" %}
{% block title %}Tools{% endblock %}

{% block content %}
<hr>
<div class="uk-container">
    <h2>ツール一覧</h2>
    <a href class="uk-display-block uk-card uk-card-body uk-card-default uk-link-toggle uk-width-medium">
        <h3 class="uk-card-title"><span class="uk-link-heading">アンケート作成</span></h3>
        <p>アンケートを作成します。
        相手を指定して回答を要求することができます。</p>
    </a>
</div>
{% endblock %}

intra/front/templates/front/top.html
{% extends "front/base_account.html" %}

{% block title %}トップ{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">Top画面</h1>
    <a href="{% url 'front:login' %}" class="btn btn-outline-primary">ログイン</a>
</div>
{% endblock %}